### ISSUE TITLE
正确姿势使用Gitlab CI

### ISSUE THREAD

**Issue by orangemi** [orangemi/orangemi.github.io#6]
## 前言
`Gitlab CI` 是一个好工具，Teambition大多数项目的自动构建和部署开发环境都会使用。但我们在使用上有很多`安全`问题

## 我们的问题
1. Teambition构建的时候需要安装依赖，在安装依赖的时候需要对应的权限，创建了一个超级image，赋予了gitlab的最高读取权限，可以读取任意repo。这样造成的问题是repo泄漏，当我们招募了一个实习生同学，虽然管理员只赋予了该同学某一个repo的权限，以及CI权限时，与此同时，也泄漏了整个gitlab的代码库。

2. Teambition后端项目都是基于docker标准化镜像，在构建过程中需要使用docker命令构建镜像以及发布镜像，而runner本身也是一个docker运行时，这样就是一个docker-in-docker的环境。Teambition在runner运行时将`宿主机`的docker sock 挂载到runner内部，而runner内部只需要有docker-cli就可以运行docker命令了。虽然方便，但泄漏了宿主机的docker，runner在执行中可能对宿主机造成攻击甚至是删除宿主机数据。

3. Teambition和大多数互联网公司一样，有一支自己的运维团队，所有发布和线上环境的操作都是运维操作的（或运维工具），开发同学在构建好镜像后需要触发运维的部署脚本才能发布。Gitlab CI 也有CI/CD的能力，为什么不使用呢？到底哪里阻碍了DevOps的发展？

### 解决依赖安装及权限范围
解决依赖安装，这个话题在gitlab-ce的issue列表中存在时间也[非常的久远](https://gitlab.com/gitlab-org/gitlab-ce/issues/18994)，至今有2,3年了，也经历了[重大重构](https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html)。目前官方的方案就是利用`CI_JOB_TOKEN`。我们从头整理需求，这里的需要解决的场景有：

- 开发同学需要在本地开发
- 开发同学需要在本地构建
- CI需要在CI环境运行测试
- CI需要在CI环境构建
- 开发同学不能通过CI工具越权

我们再看看`CI_JOB_TOKEN`在CI中的能力吧，我觉得在gitlab的文档没有特别指出这个token的用法和权限范围。我来来回回阅读了好几遍算是理解了，最后经过实际验证得到结论：`CI_JOB_TOKEN`的权限范围就是用户的权限范围，两者是等价的。除了这个特性，`CI_JOB_TOKEN`还有几个特征可以利用：
- 只在构建过程中有效，从构建开始到构建结束。
- 在构建过程中不可见，不可打印在日志中。
- 如果是某个用户触发导致构建，CI_JOB_TOKEN是触发用户的权限范围。
- 如果是定时任务schedule或API触发trigger，CI_JOB_TOKEN以那trigger的主人视权限范围
- CI_JOB_TOKEN亦可用于gitlab docker registry
- CI_JOB_TOKEN等价于用户private access token (repo only)

总的来说CI_JOB_TOKEN能够满足上面提到的场景。那应该如何做呢？

### 本地运行时私有依赖
我们就拿nodejs项目来说吧。假如我们有给nodejs项目引用了一个私有仓库private-node-lib，通常通过`npm install --save git+ssh://git@gitlab-host/private-group/private-node-lib.git#v0.3.0`，最终该项目的package.json片段如下：
```json
{
  "name": "demo-repo",
  "version": "1.0.0",
  "dependencies": {
    "@tb/private-library": "git+ssh://git@gitlab-host/private-group/private-node-lib.git#v0.3.0"
  }
}
```

对于新接触这个项目的开发人员在本地开发时，使用`npm install`时，`git`会使用用户gitlab的git登录身份验证是否有权限，这一点原来也是OK的，如果实习生拥有demo-repo的权限，却没有依赖库的权限，将不能调试开发demo-repo项目，这是理想中的。No problem for local development!

### 本地构建镜像的私有依赖
开发人员需要构建镜像时会有问题，一般我们的`Dockerfile`如下结构：
```Dockerfile
FROM node:10.15.3-alpine as dependency
RUN apk --no-cache add git

WORKDIR /app
COPY package* /app/

RUN npm install --production

# ready for production
FROM node:10.15.3-alpine

WORKDIR /app
COPY --from=dependency /app/node_modules /app/node_modules
COPY .  /app/

EXPOSE 80 443
CMD [ "npm", "start" ]
```

如果同学不理解分步构建docker镜像的，请移步https://docs.docker.com/develop/develop-images/multistage-build ，或等下回详细介绍分步构建Docker镜像。

在本地开发环境，这个Dockerfile的构建将会失败，它的问题在于`RUN npm install`这一步，由于在镜像内执行`npm install`失去了宿主机上任何信息，包含已经登录过gitlab的ssh身份信息。那应该如何解决呢？

神奇的地方出现了，我们可以通过`git config`命令替换`remote-url`的方式获取权限，这一步需要用`private access token`来代替自己的ssh私钥获取相应的repo权限。具体方法如下：

首先，我们要在gitlab中生成一个`private access token`，具体方法参考：https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html ，这里稍稍翻译一下，在gitlab中右上角个人setting页面中找到access_token，然后生成一个read_repositry权限的access_token，并设置环境变量中`export CI_JOB_TOKEN=xxxx`，可以在你的`~/.bashrc`中添加这一行。

第二，在Dockerfile 中在`npm install`之前一步git config的替换
```
RUN git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-host/".insteadOf "git://gitlab-host:" \
  && npm install
```

第三，在执行构建镜像时，将环境变量因素加入到构建过程中（可以不填写具体的值）

```
docker build -t some_repo --build-arg CI_JOB_TOKEN .
```

第四，虽然在命令行中指定了build_arg，但还需要在dockerfile 中确认使用arg参数
```Dockerfile
FROM node:10.15.3-alpine as dependency
RUN apk --no-cache add git
ARG CI_JOB_TOKEN
...
```

完成上面这些步骤后，可以解决在本地环境中的构建问题，有同学会觉得会有些麻烦，因为感觉只需要自己的ssh私钥加入构建过程中就能解决，是的，但我们还要同时解决CI构建时的问题，个人ssh不能用于CI构建，下面我们来解决一下CI环境下运行和构建问题。

### CI环境中使用docker命令行
在讨论gitlab构建镜像前，首先要在CI环境中执行docker命令，而runner本身运行在docker中，这样就形成`docker-in-docker`的环境，根据[Gitlab官方文档](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html)指导， 构建docker是最好不要使用宿主机上的docker.sock文件，因为这会泄漏宿主机的root权限，可能会有严重的安全隐患。官方推荐使用docker service作为依赖创建出一个纯净并隔离的环境。最基础的ci配置如下：

```yaml
build-image:
  stage: build-image
  image: docker:stable # 只用docker官方镜像作为基础镜像，拥有docker命令行
  services:
    - name: docker:dind # 使用docker:dind作为依赖service，提供2375的tcp端口
      command: ["--insecure-registry=private-docker-registry-host"]
  variables:
    DOCKER_HOST: tcp://docker:2375 # 默认使用tcp来链接docker-machine
    DOCKER_DRIVER: overlay2 # 优化docker-machine文件系统的优化
  before_script:
    - docker info
    - docker login -u {DOCKER_USER} -p ${DOCKER_PASSWORD} {private-docker-registry-host}
  script:
    - docker build -t .

```

虽然在官方指导中，这个方式需要在注册runner时添加`--docker-privileged`参数，这个参数仍然会造成安全隐患，但目前只能期待docker官方想办法解决。

上述yaml中使用到了`docker:dind`这个镜像，这个镜像和原生`docker:stable`镜像没有功能上的差异，只是默认打开了tcp远程端口，如果在主机上长期开放tcp端口势必会带来安全隐患，现在只是在CI生命周期中开放，且外网无法联通，没有太大问题。

另外上述yaml中还用到了一个私有docker registry镜像地址，为的是方便推拉私有镜像，这里作者没有研究gitlab的docker registry的注册方法，认为他们是独立的2个服务。

### CI环境中使用构建docker镜像
有了上面2步的准备工作，已经可以在CI环境中正常使用`docker build`命令了

## 总结
感觉写的已经有点长了，还有如何在CI中利用`docker cache`的问题还没有解决，这方面知识确实比较零散，无法简单的用一两句话说完。

PS. 这里好像忘了提devOps的问题，是的，这个问题更离散，还需读者拥有k8s或运维领域的相关知识。
